version: '3'

services:
  muscle:
    build:
      context: .
      dockerfile: Dockerfile
    #command: bash -c "./muscle_path"
    command: tail -f /dev/null
    #restart: always
    image: muscle
    container_name: muscle
    environment:
      - DISPLAY=:0
    volumes:
      - ./tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - muscle-network
    #command: ["./muscle_path"]

networks:
  muscle-network:
    driver: bridge
    